name: animal_market
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.14+14

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  oktoast: ^3.4.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1
  date_picker_timeline: ^1.2.6
  share_plus: ^10.1.4
  dropdown_button2: ^2.3.9
  infinite_scroll_pagination: ^4.1.0
  table_calendar: ^3.0.9
  video_player: ^2.9.2
  http: ^1.2.1
  package_info_plus: ^8.1.2
  device_info_plus: ^10.1.0
  lottie: ^3.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.0
  overlay_support: ^2.1.0
  flutter_datetime_picker_plus: ^2.2.0
  razorpay_flutter: ^1.3.7
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^27.1.51
  webview_flutter: ^4.10.0
  google_places_flutter: ^2.0.9
  open_file: ^3.5.10
  dio: ^5.5.0+1
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4
  app_links: ^6.3.2
  flutter_html_table: ^3.0.0
  audioplayers: ^6.4.0
  flutter_sound: ^9.2.13
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf

    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf

    - family: Inter-Italic
      fonts:
        - asset: assets/fonts/Inter-Italic.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-packag