
import 'dart:convert';
import 'package:animal_market/core/export_file.dart';
import 'package:animal_market/services/api_service.dart';
const Map<String, String> fallbackStrings = {
  "appName": "Animal Market",
  "appVersion": "Version",
  "enterEmail": "Enter an email",
  "enterEmailValid": "Enter a valid email",
  "account": "Account",
  "language": "Language",
  "faq": "FAQ",
  "myFavourites": "My",
  "myFavourites1": "Favourites",
  "helpAndSupport": "Help And",
  "helpAndSupport1": "Support",
  "shareApp": "Share",
  "app": "App",
  "asDoctor": "As Doctor",
  "termConditions": "Terms And",
  "conditions": "Conditions",
  "termConditions1": "Terms And Conditions",
  "rateApp": "Rate",
  "aboutUs": "About",
  "us": "Us",
  "aboutUs1": "About Us",
  "selectedReason": "Selected reason is required",
  "logout": "Logout",
  "asUser": "As User",
  "delete": "Delete",
  "areSure": "Are Your Sure You want To  ",
  "no": "No",
  "yes": "Yes",
  "sell": "Sell",
  "submit": "Submit",
  "logout1": "Logout",
  "pleaseUpdate": "Please Update Your App",
  "newAppVersion": "New App Version",
  "downloadNow": "Download Now",
  "appointment": "Appointment",
  "bookAppointmentDate": "Book Appointment Date",
  "availableTimeSlots": "Available Time Slots",
  "noTimeSlots": "No time slots available",
  "pleaseSelectTimeSlot": "Please select time slot",
  "conti": "Continue",
  "noAppointmentYet": "No Appointment Yet",
  "bookAppointment": "Book Appointment",
  "appointmentDateAndTime": "Appointment Date & Time",
  "cancelled": "Cancelled",
  "cancelAppointment": "Cancel Appointment ",
  "enterOTP": "Enter OTP ",
  "enterOTPValid": "Enter a valid OTP",
  "yourLocation": "Your Location",
  "currentLocation": "Current Location",
  "usingGPS": "Using GPS",
  "searchAddress": "Search New Address",
  "indiaTrusted": "India's Trusted",
  "onlineMarket": "Online Market for",
  "buyingSelling": " Buying & Selling ",
  "animals": "Animals",
  "loginOrSignUp": "Login Or Sign Up",
  "enterMobileNo": "Enter Mobile Number",
  "enterValidMobile": "Enter Valid Mobile No.",
  "byContinuing": "By Continuing, You Agree To Our ",
  "termsOfUse": "Terms of Use",
  "privacyPolicy": "Privacy Policy",
  "otpVerification": "OTP Verification",
  "weHaveSentVerificationCode": "We have sent a verification code to",
  "checkTextMessages": "Check Text Messages For Your OTP",
  "didntGetOTP": "Didn’t get the OTP ? ",
  "resendOtp": "Resend OTP",
  "resendSmsIn": "Resend SMS in",
  "selectYourPreferred": "Select your preferred",
  "noLanguageFound": "No Language Found ",
  "welcomeTo": "Welcome To ",
  "enterName": "Enter Name",
  "yourName": "Your Name",
  "onlyAlphabets": "Only alphabets are allowed",
  "noDataFound": "No Data Found",
  "buy": "Buy",
  "cattle": "Cattle",
  "otherAnimal": "Other Animals",
  "nearYou": "Near You",
  "seeAll": "See All",
  "searchCattle": "Search Cattle in Specific Area",
  "selectLocationOnMap": "Select Location On Map",
  "searchAnimals": "Search For “ Animal”",
  "cattleMarket": "Cattle Market",
  "negotiable": "Negotiable",
  "call": "Call",
  "cattleDetails": "Cattle Details",
  "priceNegotiable": "Price Negotiable",
  "moreInformation": "More  Information",
  "age": "Age",
  "years": "years",
  "milkCapacity": "Milk Capacity",
  "animalWithBaby": "Animal with Baby",
  "deliveredBaby": "Delivered Baby",
  "vaccinated": "Vaccinated",
  "pregnant": "Pregnant",
  "gender": "Gender",
  "breed": "Breed",
  "pregnancy": "Pregnancy",
  "healthStatus": "Health Status",
  "description": "Description",
  "sellerInformation": "Seller Information",
  "memberId": "Member ID ",
  "address": "Address",
  "filter": "Filter",
  "animalCategory": "Animal Category",
  "select": "Select",
  "clear": "Clear",
  "apply": "Apply",
  "minMilkCapacity": "Min Milk Capacity",
  "maxMilkCapacity": "Max Milk Capacity",
  "enter": "Enter",
  "minPrice": "Min Price",
  "maxPrice": "Max Price",
  "searchLocation": "Search location",
  "crop": "Crops",
  "otherCrops": "Other Crops",
  "searchCropSpecificArea": "Search Crop in Specific Area",
  "searchCrop": "Search For “ Crop”",
  "pet": "Pet",
  "otherPets": "Other Pets",
  "searchPetSpecificArea": "Search Pet in Specific Area",
  "searchPet": "Search For “ Pet”",
  "selectYour": "Select Your ",
  "service": "Service",
  "callUs": "Call Us",
  "chatUs": "Chat Us",
  "emailUs": "Email Us",
  "storagePermissionRequired": "Storage permission required!",
  "downloadFile": "Downloading file...",
  "fileSavedFolder": "File saved to Downloads folder!",
  "failedDownloadFile": "Failed to download file",
  "frequentAskedQuestion": "Frequently Asked Questions",
  "knowYourCattleHeathStatus": "Know Your Cattle Heath Status",
  "scanNow": "Scan Now",
  "myReports": "My Reports",
  "noReportFound": "No Report Found",
  "reportId": "Report ID",
  "transactionId": "Transaction Id",
  "noteByYou": "Note By You",
  "payment": "Payment",
  "downLoadReport": "Download Report",
  "sellerIncompleteProfile": "Seller incomplete Profile",
  "animalListed": "Animal Listed",
  "callsReceived": "Calls Received",
  "views": "Views",
  "areYourSureYouWantToDeleteThisListing": "Are Your Sure You want To Delete This listing ?",
  "benefitsOfSellingInAnimalMarket": "Benefits of selling in animal market",
  "noScams": "No Scams",
  "profitH": "100% Profit",
  "noFraud": "No Fraud",
  "commission": "0% Commission",
  "noBrokerage": "No Brokerage",
  "directSell": "Direct Sell",
  "editInfo": "Edit Info",
  "markToSell": "Mark To Sell",
  "sold": "Sold",
  "cancel": "Cancel",
  "underVerified": "Under Verified",
  "verified": "Verified",
  "petSuccessfullyCreated": "Pet Successfully Created",
  "thankYou": "Thank You",
  "yourPetIsRegistered": "Your Pet is Registered",
  "waitFor30Minutes": "Wait for 30 Minutes ",
  "petIsUnderVerification": "Your pet is under verification",
  "shareYouPetToSellFast": "Share Your Pet To Sell Fast",
  "sellNow": "Sell Now",
  "petListed": "Pet Listed",
  "myDashboard": "My Dashboard",
  "allListing": "All Listing",
  "underVerify": "Under Verify",
  "edit": "Edit",
  "sellYourPet": "Sell Your Pet",
  "listingPurpose": "Listing Purpose",
  "selectPurposeListing": "Select Purpose Listing",
  "petCategory": "Pet Category",
  "selectPetCategory": "Select Pet Category",
  "petBreed": "Pet Breed",
  "selectPetBreed": "Select Pet Breed",
  "enterAge": "Enter Age",
  "ageType": "Age Type",
  "vaccination": "Vaccination",
  "selectVaccine": "Select Vaccine",
  "vaccineName": "Vaccine Name",
  "enterVaccineName": "Enter Vaccine Name",
  "vaccineDate": "Vaccine Date",
  "sellerType": "Seller Type",
  "selectSellerType": "Select Seller Type",
  "sellerName": "Seller Name",
  "enterSellerName": "Enter Seller Name",
  "sellerMobileNumber": "Seller Mobile Number",
  "enterSellerMobileNumber": "Enter Seller Mobile Number",
  "sellerValidWhatsAppNumber": "Seller Valid WhatsApp Number",
  "enterSellerValidWhatsAppNumber": "Enter Seller Valid WhatsApp Number",
  "sellPrice": "Sell Price",
  "photoAtLeastOne": "Photo (at least one)",
  "itSellsFastIf": "It sells fast if you post a good photo",
  "uploadImage": "Upload Image",
  "video": "Video",
  "record": "(record whole animal and its parts & Surroundings)",
  "descriptionOptional": "Description (Optional)",
  "enterDescription": "Enter Description",
  "changeLocation": "Change Location",
  "noteThis": "Note: This app only helps you find pet sellers. All transactions, payments, and delivery are handled by the seller outside the platform",
  "enterPackingCharges": "Enter Packing Charges",
  "packingCharges": "Packing Charges",
  "enterShippingCharges": "Enter Shipping Charges",
  "shippingOtherCharges": "Shipping & Other Charges",
  "selectDeliveryType": "Select Delivery Type",
  "locationDelivery": "Location & Delivery",
  "selectTrainingType": "Select Training Type",
  "trainingType": "Training Type",
  "trained": "Trained",
  "goodWithOtherPets": "Good with Other pets",
  "requiresSpecialCare": "Requires Special Care",
  "neuteredSpayed": "Neutered/Spayed",
  "deformed": "Deformed",
  "microChipped": "Micro chipped",
  "addMoreInfo": "Add More Information (Optional)",
  "shipNationwide": "Ship Nationwide",
  "deliveryAvailable": "Delivery Available",
  "pickUpOnly": "Pick-up Only",
  "houseTrained": "House Trained",
  "guardTrained": "Guard Trained",
  "defenceTrained": "Defence Trained",
  "days": "Days",
  "months": "Months",
  "forSale": "For Sale",
  "forAdoption": "For Adoption",
  "forMating": "For Mating",
  "individual": "Individual",
  "licensedBreeder": "Licensed Breeder",
  "registeredPetShop": "Registered Pet Shop",
  "rescueOrganization": "Rescue Organization",
  "notVaccinated": "Not Vaccinated",
  "partiallyVaccinated": "Partially Vaccinated",
  "fullyVaccinated": "Fully Vaccinated",
  "male": "Male",
  "female": "Female",
  "other": "Other",
  "cropSuccessfullyCreated": "Crop Successfully Created",
  "yourCropIsRegistered": "Your Crop is Registered",
  "cropIsUnderVerification": "Your crop is under verification",
  "shareYourCropToSellFast": "Share Your Crop To Sell Fast",
  "cropListed": "Crop Listed",
  "sellYourCrop": "Sell Your Crop",
  "cropCategory": "Crop Category",
  "cropName": "Crop Name",
  "enterCropName": "Enter Crop Name",
  "cropVariety": "Crop Variety",
  "quantityType": "Quantity Type",
  "quantity": "Quantity",
  "enterQuantity": "Enter Quantity",
  "cropOrganic": "Crop Organic",
  "isOrganic": "Is Organic",
  "qualityTested": "Quality Tested",
  "isQualityTested": "is Quality Tested",
  "storageCondition": "Storage Condition",
  "cropCondition": "Crop Condition",
  "fresh": "Fresh",
  "dry": "Dry",
  "processed": "Processed",
  "cropAge": "Crop Age",
  "farmer": "Farmer",
  "reseller": "Reseller",
  "warehouse": "Warehouse",
  "open": "Open",
  "coldStorage": "Cold Storage",
  "notApplicable": "Not Applicable",
  "lessThanThreeMonths": "Less than 3 months",
  "threeToSixMonths": "3-6 Months",
  "sixToTwelveMonths": "6-12 Months",
  "moreThanOneYear": "More than 1 Year",
  "notification": "Notification",
  "noNotificationYet": "No Notification Yet",
  "yourNotificationWill": "Your Notification will appear here once you've received them.",
  "backToHome": "Back To Home",
  "myFavourite": "My Favourites",
  "petDetails": "Pet Details",
  "petMarket": "Pet Market",
  "category": "Category",
  "subCategory": "Sub Category",
  "cropMarketplace": "Crop Marketplace",
  "farmingType": "Farming Type",
  "verifyStatus": "Verify Status",
  "dryOrWet": "Dry Or Wet",
  "remainingTime": "Remaining Time",
  "remainingTimeLeftToHarvest": "Remaining  Time Left To Harvest",
  "transportationFacility": "Transportation Facility",
  "searchFor": "Search For “Words”",
  "viewPdf": "View PDF",
  "viewDocument": "View Document",
  "home": "Home",
  "knowledge": "Knowledge",
  "favorite": "Favorite",
  "document": "Document",
  "image": "Image",
  "addEvent": "Add Event",
  "eventName": "Event Name*",
  "typeTheNoteHere": "Type The Note Here...",
  "date": "Date",
  "time": "Time",
  "enterEventDate": "Enter Event Date",
  "startTime": "Start Time",
  "enterStartTime": "Enter Start Time",
  "remindsMe": "Reminds Me",
  "createEvent": "Create Event",
  "deleteEvent": "Delete",
  "deleteEvent1": "Event?",
  "eventDetails": "Event Details",
  "eventCalendar": "Event Calendar",
  "remove": "Remove",
  "pleaseEnterTitle": "Please enter title",
  "pleaseEnterDescription": "Please enter description",
  "pleaseEnterEventDate": "Please enter event date",
  "pleaseEnterStartTime": "Please enter start time",
  "editProfile": "Edit Profile",
  "update": "Update",
  "emailAddress": "Email Address",
  "number": "Number",
  "whatsAppNumber": "WhatsApp Number ",
  "dateBirth": "Date Of Birth",
  "enterDateBirth": "Enter Date of Birth",
  "pleaseSelectReasonTo": "Please select reason to ",
  "recordVideo": "Record",
  "recordVideo1": "Video",
  "giveInformation": "Give",
  "giveInformation1": "Information",
  "paymentS": "Payment",
  "getReport": "Get",
  "getReport1": "Report",
  "chooseTypeOfReport": "Choose Type Of Report",
  "ifAny": "(if any information type here below text box)",
  "pleaseSelectReportType": "Please select report type",
  "addMoreInformation": "Add more information",
  "selectedPlan": "Selected Plan",
  "pay": "Pay",
  "benefitForYou": "Benefit For You",
  "paymentDetails": "Payment Details",
  "fees": "Fees",
  "gST": "GST",
  "totalFee": "Total Fee",
  "accept": "Accept",
  "payNow": "Pay Now",
  "yourPaymentIsSuccessfullyDone": "Your Payment is Successfully Done",
  "waitForReportFromDoctor": "Wait for Report from Doctor",
  "captureThe": "(capture the area where there is problem)",
  "pleaseUploadVideo": "Please upload video",
  "pleaseUploadImage": "Please upload images",
  "allPost": "All Post",
  "myPost": "My Post",
  "details": "Details",
  "enterYourReplyHere": "Enter your reply here",
  "community": "Community",
  "marketCommunity": "Market Community",
  "editPost": "Edit Post",
  "createPost": "Create Post",
  "readCommunityGuidelinesBeforePosting": "Read Community Guidelines Before Posting!",
  "enterYourPostHere": "Enter Your Post Here",
  "post": "Post",
  "doctors": "Doctors",
  "namaste": "Namaste",
  "myAppointment": "My Appointment",
  "slots": "Slots",
  "customDateFilter": "Custom Date Filter",
  "startDate": "Start Date",
  "endDate": "End Date",
  "createDoctorAccount": "Create Doctor Account",
  "name": "Name",
  "nameIsRequired": "Name is required",
  "clinicName": "Clinic Name",
  "enterClinicName": "Enter Clinic Name",
  "clinicNameIsRequired": "Clinic Name is required",
  "workExperience": "Work Experience",
  "enterFees": "Enter Fees",
  "states": "State",
  "city": "City",
  "enterAddress": "Enter Address",
  "addressIsRequired": "Address is required",
  "postCode": "Post Code",
  "enterPostCode": "Enter Post Code",
  "postCodeIsRequired": "Post Code is required",
  "aboutYourself": "About Yourself",
  "photoClinic": "Photo Clinic",
  "youPostAGoodPhotos": "you post a good photos",
  "pleaseUploadAllImages": "Please upload all images",
  "pleaseSelectExperience": "Please select experience",
  "pleaseSelectState": "Please select state",
  "pleaseSelectCity": "Please select city",
  "searchForNameID": "Search For “Name ID”",
  "chooseYourSubscription": "Choose Your Subscription",
  "bestSelling": "Best Selling",
  "benefitsOfPlan": "Benefits of plan in animal market",
  "buyASubscription": "Buy a subscription",
  "moreCallsWillCome": "More Calls",
  "moreCallsWillCome1": "Will Come",
  "listShowOnTop": "List Show",
  "listShowOnTop1": "On Top",
  "verifiedSign": "Verified",
  "verifiedSign1": "sign",
  "pleasSelectAPlan": "Please select a plan",
  "drProfile": "Doctor Profile",
  "totalAppointment": "Total Appointment",
  "todayAppointment": "Today Appointment",
  "createY": "Create your Account To start booking",
  "withAnimalMarket": "with animal Market ",
  "youAreNotRegisteredAs": "You Are Not Registered As",
  "dayAvailableTimeSlots": "Day / Available Time Slots",
  "save": "Save",
  "searchForDoctors": "Search For “ Doctors”",
  "chat": "Chat",
  "doctorDetails": "Doctor Details",
  "aboutDoctor": "About Doctor",
  "viewAll": "View All",
  "sellYourCattle": "Sell Your Cattle",
  "lactation": "Lactation (Pregnancy History) ",
  "isMilk": "Milk",
  "milkCapacityPer": "Milk Capacity (Per Day)*",
  "enterMilkCapacityPerDay": "Enter Milk Capacity Per Day",
  "animalHeathStatus": "Animal Heath Status",
  "isItVaccinated": "Is it Vaccinated ?",
  "doesItHaveACalf": "Does it have a calf ?",
  "isItPregnant": "Is it Pregnant ?",
  "hasItDelivered": "Has it Delivered ?",
  "cattleSuccessfullyCreated": "Cattle Successfully Created",
  "yourAnimalIsRegistered": "Your Animal is Registered",
  "waitAnimalIsUnderVerification": "Your animal is under verification",
  "shareYourAnimalToSellFast": "Share Your Animal To Sell Fast",
  "sellerProfile": "Seller  Profile",
  "addYourVoiceMessage": "Add Your Voice Message",
  "voiceDescription": "Voice Description",
  "enterBreedName": "Enter Breed Name"
};

class TranslationsProvider extends ChangeNotifier {
  Map<String, String> translations = {};
  String currentLang = 'hi';

  String tr(String key) {
    return translations[key] ?? fallbackStrings[key] ?? key;
  }
  Future<void> loadLanguage(String languageCode) async {
    try {
      var result = await ApiService.translations(languageCode);
      var json = jsonDecode(result.body);
      if (json["status"] == true && json["data"] is Map) {
        final Map<String, dynamic> data = json['data'];
        translations = data.map((k, v) => MapEntry(k, v.toString().replaceAll('[[NEWLINE]]', '\n')));
        notifyListeners();
      } else {
        Log.console('Failed to load translations: status false or invalid data');
      }
    } catch (e) {
      Log.console('Exception loading translations: $e');
    }

    notifyListeners();
  }

}

